language: node_js

node_js:
  - node

before_install:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan -p $DEPLOY_PORT $DEPLOY_HOST >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - openssl aes-256-cbc -K $encrypted_370926310f75_key -iv $encrypted_370926310f75_iv -in deploy_rsa.enc -out ~/.ssh/id_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ~/.ssh/id_rsa
  - ssh-add ~/.ssh/id_rsa

script:
  - echo 'completed'

deploy:
  provider: script
  script: 
    - ssh -p $DEPLOY_PORT $DEPLOY_USER@$DEPLOY_HOST "cd $DEPLOY_PATH && git fetch && git reset --hard origin/master"
  on:
    branch: master

notifications:
  slack: baijunyao:RwKXeTdqgzVG1gAgGTyry4B7
