name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Build
        run: |
          yarn docs:build:laravel-bjyblog
          yarn docs:build:laravel-scout-elasticsearch
          yarn docs:build:thinkphp-bjyblog
      - uses: azure/docker-login@v1
        with:
          username: baijunyao
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - uses: azure/docker-login@v1
        with:
          login-server: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.ALIYUN_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_CONTAINER_REGISTRY_PASSWORD }}
      - name: Push Docker Images
        run: |
          docker build . -t baijunyao/docs
          docker tag baijunyao/docs registry.cn-beijing.aliyuncs.com/baijunyao/docs
          docker push baijunyao/docs
          docker push registry.cn-beijing.aliyuncs.com/baijunyao/docs

  notify:
    name: Slack Notify
    runs-on: ubuntu-latest
    needs: [ build ]
    if: always()
    steps:
      - name: Slack Notify
        uses: baijunyao/action-slack-notify@v3.0.0
        if: always()
        with:
          slack_channel_id: CJWC21HHT
          slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          github_context: ${{ toJson(github) }}
