name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Build
        run: |
          yarn docs:build:laravel-bjyblog
          yarn docs:build:laravel-print
          yarn docs:build:laravel-scout-elasticsearch
          yarn docs:build:thinkphp-bjyadmin
          yarn docs:build:thinkphp-bjyblog
          tar -zcvf dist.tar.gz dist
      - name: SSH Init
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: SCP
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "rm -rf /tmp/docs && mkdir -p /tmp/docs"
          scp dist.tar.gz ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/tmp/docs/
      - name: Deploy
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cd /tmp/docs && tar -zxvf dist.tar.gz && rm -rf /laravel-bjyblog/site/public/docs/ && mv /tmp/docs/dist /laravel-bjyblog/site/public/docs/"

  notify:
    name: Slack Notify
    runs-on: ubuntu-latest
    needs: [ build ]
    if: always()
    steps:
      - name: Slack Notify
        uses: baijunyao/action-slack-notify@v3.0.0
        if: always()
        with:
          slack_channel_id: CJWC21HHT
          slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          github_context: ${{ toJson(github) }}
